### ISSUE TITLE
Search for string keys of varying length

### ISSUE THREAD

**Issue by Valentin-D-Richard** [MrTomRod/BinaryFileSearch#3]
The sort suggested by the current README does not make BinaryFileSearch work on keys (first column) of varying length.

I figured out this is because the module expects strict prefixes to come first, while bash `sort` puts them at the end. For example, the module expects
```
ban
banana
cat
```
whereas `sort` produces
```
banana
ban
cat
```

We can obtain the expected sort by first padding the keys with whitespaces (assuming the keys don't have whitespaces or characters strictly before in ASCII) in awk, and removing them after sorting:
```bash
awk 'BEGIN {FS=OFS=","} {s = sprintf("%*s",N-length($1),""); print $1 s,$2}' input.csv \
 | LC_ALL=C sort --key=1 --field-separator=','
 | sed 's/ //g' > output.csv
```
where `N` is the max size of keys, which can be obtained using:
```bash
cut -d ',' -f 1 input.csv | wc -L
```

**Comment by MrTomRod** [comment]
But if you sort the file according to the instructions of the README, I get the correct result!

```bash
$ echo -e "ban\nbanana\ncat" > file.txt
$ LC_ALL=C sort --key=1 --field-separator=$'\t' --output=file.txt.sorted file.txt
$ cat file.txt.sorted
ban
banana
cat
```

**Comment by Valentin-D-Richard** [comment]
Right, sorry for that bad example. Here is an example file `input.csv`, which actually better reflects my data.

```
a*,d
a,d
a2,d
```

The command line `LC_ALL=C sort --key=1 --field-separator=$',' input.csv` prints the same result as the input, whereas the following would be expected:

```
a,d
a*,d
a2,d
```

I found the explanation: the key specification of `sort` expects 2 positions, the starting position (here field 1) and the stopping position. By default, the stopping position is the end of the line, but we want to stop at the end of field 1. So the right command line is:

```bash
LC_ALL=C sort --key=1,1 --field-separator=$',' input.csv
```

You can check that it works as expected on `input.csv`. I advise you to change your README with this fix.

**Comment by MrTomRod** [comment]
Fantastic, thanks for discovering and fixing the bug!!! I updated the README and created a [test script](https://github.com/MrTomRod/BinaryFileSearch/blob/master/test/compare_bash_sort_with_python.py) that compares bash and python sort.
